### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by wyp19930313** [bigpon/QPNet#1]
I failed to achieve the results in the paper when I trained the model myself. Can you provide a trained model?

**Comment by bigpon** [comment]
Sure, I will upload a pre-trained model (trained w/ VCC2018 corpus) before next week.

**Comment by wyp19930313** [comment]
Wow, thank you from the bottom of my heart!

**Comment by bigpon** [comment]
You are welcome.
I already uploaded the pre-trained models (trained with VCC2018 corpus) and generated utterances.
If the pre-trained models work well, I will close this issue in next week.
